name: ultra
description: "Used to be aggressive \u2014 now 'ultra' gentle :)"
depth: 13
crop: 0.02
smooth_iters: 0
adaptive: true
adaptive_params:
  iters: 4
  low_q: 0.28
  high_q: 0.93
  gamma: 0.95
cloud_cleanup:
  height_q: 0.95
  low_density_q: 0.2
